### ISSUE TITLE
Symbol not found: ____chkstk_darwin on mac

### ISSUE THREAD

**Issue by travisbrady** [tmattio/spin#55] opened 2020-02-25 22:30 UTC
I received the error below when trying to create a new project on a late 2015 Mac running Sierra.

This is with a fresh install of spin via `brew`

Error:
```
$ spin new native myspin
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/spin
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/spin
  Expected in: /usr/lib/libSystem.B.dylib

[1]    27181 abort      spin new native myspin
```

Machine details:
```
$ uname -a
Darwin AUSC02QRF6FG8WP 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun  2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
```

**Comment by tmattio** [comment] 2020-03-06 00:06
Hi @travisbrady!

Thanks for opening the issue. Seems to be the same as #22 

From the information I've gathered, I think it's because the macOS's version Spin's binaries were compiled on is not compatible with your macOS's version.

I will look into it more and might need your help to try a few things as it's difficult for me to reproduce the error.

**Comment by tmattio** [comment] 2020-03-09 05:30
@travisbrady I just released a new version of Spin with a potential fix for this, could you try installing it again?

```
brew install tmattio/tap/spin
```

**Comment by bentxt** [comment] 2020-03-09 23:02
> could you try installing it again?

Hi, I hope its ok to chime in. Spin doesn't run when installed with brew:

```
 brew install tmattio/tap/spin
~/l/s/spin.git (master)> spin
dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/spin (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/spin (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
fish: 'spin' terminated by signal SIGABRT (Abort)
```

esy is fine,

```
esy build
esy start
```

but its unclear how to proceed now. How to install with esy? `esy install` doesn't seem to make spin available.

**Comment by tmattio** [comment] 2020-03-09 23:19
@bentxt This is with the latest version of Spin (0.5.0)?

If you want to install Spin from the source, you can run `esy dune install` at the root of the repository.

**Comment by bentxt** [comment] 2020-03-10 00:23
I may forgot to brew upgrade?

```
brew upgrade
[I] bkb@quantum ~/l/spin> brew install tmattio/tap/spin
```

**Comment by bentxt** [comment] 2020-03-10 00:24
spin --version is weird ...

```
spin --version
%%VERSION%%
```

**Comment by tmattio** [comment] 2020-03-10 00:28
@bentxt If you've installed spin with homebrew before, you'll probably need to uninstall it first with `brew uninstall tmattio-spin`, and install it again with `brew install tmattio/tap/spin` (the formula changed).

If you're seeing this version, I assume you're installing from the sources. When we release we run `esy dune subst` which will replace the watermarks in the code with their corresponding values. In particular, the `%%VERSION%%` watermark will be replaced with the version to release. But as you're installing from the sources, the version hasn't been replaced.

**Comment by tmattio** [comment] 2020-07-20 16:42
I'm going to close this for now as there's no activity. Don't hesitate to re-open if the problem persists.

**Closed as completed by tmattio** 2020-07-20 16:42 UTC
Labels: bug
