### ISSUE TITLE
Internal error, uncaught exception: unexpected sum tag

### ISSUE THREAD

**Issue by Splingush** [tmattio/spin#58] opened 2020-03-13 12:44 UTC
Hey folks!

When I run `spin new react` I get an

```ml
📡  Updating official templates.
Done!

😱  Ooops, an unknown error occured. You can file a bug reports at https://github.com/tmattio/spin.
Here is the stack trace in case it helps:

spin: internal error, uncaught exception:
      (Of_sexp_error
        "lib/config_file/config_file_doc.re.cst_of_sexp: unexpected sum tag"
        (invalid_sexp
          (command
            ((name "esy install")
              (description "Download and lock the dependencies.")))))
      Raised at file "sexp_conv.ml", line 203, characters 30-72
      Called from file "src/list.ml", line 376, characters 13-17
      Called from file "src/list.ml" (inlined), line 387, characters 15-31
      Called from file "lib/config_file/config_file.re" (inlined), line 40, characters 7-33
      Called from file "lib/config_file/config_file.re", line 38, characters 4-74
      Called from file "src/list.ml", line 368, characters 13-17
      Called from file "lib/source.re", line 36, characters 20-43
      Called from file "bin/commands/cmd_new.re", line 13, characters 15-41
      Called from file "lib/errors.re", line 18, characters 5-11
      Re-raised at file "lib/errors.re", line 107, characters 4-15
      Called from file "bin/commands/cmd_new.re", line 49, characters 4-84
      Called from file "cmdliner_term.ml", line 25, characters 19-24
      Called from file "cmdliner.ml", line 117, characters 32-39
```

Installed | Version
------------|-----------
spin        | `0.5.0`
Arch Linux |`5.5.8-arch1-1`
OCaml | `ocaml-base-compiler.4.08.1  4.08.1`
opam | `2.0.6`
esy | `0.6.2`
ppx_sexp_conv | `v0.13.0`
sexplib | `v0.13.0`
sexplib0 | `v0.13.0`

I get the same error regardless of installation-method: I've tried doing it through yarn (global) and through opam.

It also happens on different templates.

(Sidenote: "You can file *a bug reports*" has a typo.)

**Comment by citizen428** [comment] 2020-03-15 08:09
@tmattio Seems this is related to https://github.com/tmattio/spin/commit/f6271c15cdc19abe8958be72b12c487722d73f70#diff-a03fd0d73e697723d0baa5e249166b9d, where command was removed from `lib/config_file/config_file_doc.re`, so we now can't deserialize the sexp.

Edit, just checked out the `next` branch of https://github.com/tmattio/spin-templates, were the changes made in preparation for that?

**Comment by tmattio** [comment] 2020-03-16 14:12
Hi @Splingush, thanks for reporting the issue.

Indeed the last version of Spin is incompatible with the current version of the templates and depends on the `next` branch which should be merged soon. I should have spotted that before releasing, I will add a check in the CI to prevent this from happening in the future.

Unfortunately, as there is currently no versioning of the templates, fixing this issue for 0.5.0 will break 0.4.8, so we also need to be able to versionize spin-template repository.

I will try to address this ASAP as Spin is broken for every user who updated to 0.5.0 version.

For reference, here are the issues/PR we need to complete:
- https://github.com/tmattio/spin/issues/59
- https://github.com/tmattio/spin/issues/61
- https://github.com/tmattio/spin-templates/pull/9

**Comment by tmattio** [comment] 2020-03-18 03:00
@Splingush I've just released version 0.5.1 on NPM and Homebrew, it should be working now with 0.5.0, but I recommend upgrading to 0.5.1 to avoid any problem if we push a breaking change to spin-templates.

**Comment by br1anchen** [comment] 2020-03-18 21:02
Upgrade to `0.5.1` now, but still got same `Raised at file "sexp_conv.ml", line 203, characters 30-72` error when run `spin new cli xxx` on Arch Linux 5.4.24 (Manjaro)

**Comment by tmattio** [comment] 2020-03-19 03:48
@br1anchen That's strange, I can't reproduce this with `0.5.1`.

What is the current commit of your local `spin-templates`?

```
git -C ~/.cache/spin/spin-templates rev-parse HEAD
```

It should be `8b448abb549bb8e62240601eca32e66cf68d968f`. If it's not, it means Spin failed to checkout the correct version. Do you see this message when you run `spin new cli xxx`?
```
📡  Updating official templates.
Done!
```

**Comment by br1anchen** [comment] 2020-03-19 20:57
@tmattio Thanks for the info.
The hash for `~/.cache/spin/spin-templates` is `dd8622f82c8d4ac3407b5d2514bc6a84788d9b1e` in this case. As you thought, it seems like `Spin` failed to checkout out latest `spin-templates`.
I manually check out latest master commit for `spin-templates`, then it works!
I got `would clobber existing tag` error when pulling templates before, it is a mismatch for git tags. I think that's the reason it failed.

**Comment by Splingush** [comment] 2020-03-19 21:01
> @Splingush I've just released version 0.5.1 on NPM and Homebrew, it should be working now with 0.5.0, but I recommend upgrading to 0.5.1 to avoid any problem if we push a breaking change to spin-templates.

Works for me now, cheers!

**Comment by tmattio** [comment] 2020-03-19 21:01
@br1anchen Ah, I see what happened. I created a tag `2.0.0`, then changed it to another commit. You probably cloned the repo in between.

Glad it works now :)

**Comment by tmattio** [comment] 2020-03-19 21:02
@Splingush Great, closing the issue then. Thanks for your patience!

**Closed as completed by tmattio** 2020-03-19 21:02 UTC
